spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:/mnt/databases/${DB_NAME}.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
# hibernate.show_sql=true

spring.kafka.consumer.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=${hostname}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#----------- SWAGGER ------------
springdoc.api-docs.path=/api-docs
springdoc.enable-data-rest=false
springdoc.swagger-ui.tagsSorter=alpha

implementation.type=endpoint
